'use client'

export const MENTE_MAESTRA = {
  productId: 'mente-maestra-fundador',
  slug: 'transforma-tu-vida-con-la-mente-maestra',
  title: 'La Mente Maestra',
  subtitle: 'Programa de transformación personal y propósito',
  checkoutUrl: (typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_MENTE_MAESTRA_CHECKOUT_URL : '') || '',
  priceLabel: (typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_MENTE_MAESTRA_PRICE_LABEL : '') || 'Próximamente',
  heroTitle: 'TRANSFORMA TU VIDA CON\nLA MENTE MAESTRA',
  heroSubtitle: 'Ordena tus pensamientos, fortalece tu propósito y convierte tus ideas en acciones concretas mediante un programa guiado de crecimiento, disciplina y fe.',
  heroSupport: 'Creado por Miguel Soria Martínez y conectado con el ecosistema MSM, este programa reúne reflexión, planificación, comunidad y herramientas digitales para ayudarte a avanzar con dirección.',
  ctaPrimary: 'COMENZAR MI TRANSFORMACIÓN',
  ctaSecondary: 'CONOCER EL PROGRAMA',
  waitlistText: 'UNIRME A LA LISTA DE ESPERA',
  modules: [
    { number: 1, title: 'VISIÓN Y PROPÓSITO', items: ['Identificar valores', 'Definir visión', 'Reconocer prioridades', 'Crear declaración de propósito'] },
    { number: 2, title: 'MENTE Y ENFOQUE', items: ['Ordenar pensamientos', 'Reconocer distracciones', 'Construir enfoque diario', 'Diario de reflexión'] },
    { number: 3, title: 'FE Y FUNDAMENTO', items: ['Oración', 'Gratitud', 'Principios bíblicos', 'Reflexión responsable'] },
    { number: 4, title: 'HÁBITOS Y DISCIPLINA', items: ['Rutina matutina', 'Planificación semanal', 'Seguimiento de hábitos', 'Revisión de avances'] },
    { number: 5, title: 'PROYECTO EN ACCIÓN', items: ['Convertir ideas en tareas', 'Definir metas medibles', 'Establecer fechas', 'Registrar resultados'] },
    { number: 6, title: 'COMUNIDAD MAESTRA', items: ['Encuentros autorizados', 'Acompañamiento comunitario', 'Intercambio de experiencias', 'Apoyo mediante ZAFIRO y ELIANA'] },
  ],
  benefits: [
    'Tienes muchas ideas y deseas organizarlas.',
    'Estás construyendo un proyecto personal o comercial.',
    'Deseas fortalecer hábitos y disciplina.',
    'Buscas una comunidad con valores y propósito.',
    'Quieres transformar reflexión en acción.',
    'Deseas avanzar con una estructura semanal clara.',
  ],
  bonuses: [
    { title: 'Cuaderno digital de trabajo', available: true },
    { title: 'Plantilla semanal de enfoque', available: true },
    { title: 'Guía de afirmaciones responsables', available: true },
    { title: 'Diario de gratitud', available: true },
    { title: 'Acceso a comunidad ZAFIRO', available: true },
    { title: 'Sesión introductoria grabada', available: false },
    { title: 'Contenido editorial adicional', available: false },
  ],
  faqs: [
    { q: '¿Este programa garantiza resultados financieros?', a: 'El programa ofrece herramientas de organización, reflexión y acción. Los resultados dependen de las decisiones, circunstancias y constancia de cada participante.' },
    { q: '¿Es un programa religioso?', a: 'El contenido está inspirado en valores cristianos, propósito, servicio y crecimiento personal. Cada participante conserva su libertad de pensamiento y decisión.' },
    { q: '¿Dónde se realiza la compra?', a: 'La compra se procesa de forma segura en MSM Marketplace.' },
    { q: '¿Puedo acceder desde Cuba y Estados Unidos?', a: 'El contenido digital estará disponible según conectividad, método de pago, regulación y disponibilidad de cada servicio.' },
    { q: '¿ELIANA participa en el programa?', a: 'ELIANA puede ayudar a organizar actividades, contenidos y seguimiento cuando estas funciones estén habilitadas y autorizadas.' },
  ],
  author: {
    name: 'Miguel Soria Martínez',
    title: 'Fundador de MSM MY STORE LLC',
    bio: 'Creador del ecosistema ZAFIRO. Su trabajo integra emprendimiento, tecnología, escritura, comunidad, fe y desarrollo personal.',
    profileUrl: '/perfil/miguelsoria',
  },
  membershipTitle: 'PROGRAMA FUNDADOR',
  membershipIncludes: [
    'Acceso al contenido disponible',
    'Materiales digitales',
    'Comunidad privada cuando esté habilitada',
    'Actualizaciones de la primera edición',
    'Insignia pública opcional de participante fundador',
  ],
}
