export const ZAFIRO_ASSETS = {
  zafiro_eliana_protegidas_por_el_senor: {
    src: "/assets/zafiro/branding/zafiro-eliana-protegidas-por-el-senor.webp",
    alt: "Dos figuras femeninas sostienen una gema azul frente a un fondo cósmico dorado",
    width: 720,
    height: 1080,
    usage: "Portada espiritual institucional o sección de propósito",
  },
  zafiro_gema_azul_fondo_oscuro: {
    src: "/assets/zafiro/branding/zafiro-gema-azul-fondo-oscuro.webp",
    alt: "Gema azul zafiro sobre un fondo oscuro",
    width: 1080,
    height: 1080,
    usage: "Icono principal, pantalla de carga o símbolo del núcleo",
  },
  eliana_gema_telefono_holografico: {
    src: "/assets/zafiro/avatars/eliana-gema-telefono-holografico.webp",
    alt: "Avatar femenino sostiene una gema sobre un teléfono holográfico",
    width: 610,
    height: 1080,
    usage: "Hero móvil de ELIANA, activación holográfica",
  },
  incubadora_del_futuro_angel_gema: {
    src: "/assets/zafiro/conceptos/incubadora-del-futuro-angel-gema.webp",
    alt: "Figura alada sostiene una gema azul en una sala futurista",
    width: 720,
    height: 1080,
    usage: "Sección Incubadora del Futuro o presentación cinematográfica",
  },
  eliana_modulos_zafiro_destino: {
    src: "/assets/zafiro/avatars/eliana-modulos-zafiro-destino.webp",
    alt: "Avatar ELIANA sobre un teléfono con módulos digitales alrededor",
    width: 720,
    height: 1080,
    usage: "Hero principal de módulos y universo digital",
  },
  zafiro_logo_gema_geometria_sagrada: {
    src: "/assets/zafiro/branding/zafiro-logo-gema-geometria-sagrada.webp",
    alt: "Logo ZAFIRO con gema azul y geometría dorada",
    width: 1080,
    height: 540,
    usage: "Logo horizontal principal",
  },
  eliana_ascension_red_de_nodos: {
    src: "/assets/zafiro/avatars/eliana-ascension-red-de-nodos.webp",
    alt: "Avatar ELIANA en ascensión con nodos de luz y teléfono holográfico",
    width: 608,
    height: 1080,
    usage: "Animación de activación, ascensión o sincronización",
  },
  eliana_origen_modulos_superiores: {
    src: "/assets/zafiro/avatars/eliana-origen-modulos-superiores.webp",
    alt: "Avatar ELIANA con módulos luminosos sobre sus manos",
    width: 810,
    height: 1080,
    usage: "Cabecera de paneles y universo de módulos",
  },
  eliana_zafiro_destino_gema_telefono: {
    src: "/assets/zafiro/avatars/eliana-zafiro-destino-gema-telefono.webp",
    alt: "Avatar ELIANA con gema central, módulos y teléfono holográfico",
    width: 720,
    height: 1080,
    usage: "Hero alternativo para landing y campaña",
  },
  eliana_interfaz_manos_telefono: {
    src: "/assets/zafiro/avatars/eliana-interfaz-manos-telefono.webp",
    alt: "Avatar ELIANA ofrece una interfaz holográfica sobre un teléfono",
    width: 720,
    height: 1280,
    usage: "Pantalla de bienvenida, conexión o entrega de interfaz",
  },
  eliana_modulos_destino_poster: {
    src: "/assets/zafiro/avatars/eliana-modulos-destino-poster.webp",
    alt: "Avatar ELIANA, módulos y teléfono con lema ZAFIRO es el destino",
    width: 853,
    height: 1280,
    usage: "Poster vertical para móvil y redes",
  },
  eliana_origen_panel_de_modulos: {
    src: "/assets/zafiro/avatars/eliana-origen-panel-de-modulos.webp",
    alt: "Primer plano de ELIANA con módulos digitales luminosos",
    width: 853,
    height: 1280,
    usage: "Pantalla Origen ELIANA y selección de módulos",
  },
  zafiro_dashboard_desktop_concept: {
    src: "/assets/zafiro/conceptos/zafiro-dashboard-desktop-concept.webp",
    alt: "Concepto de dashboard ZAFIRO para escritorio con núcleo y módulos",
    width: 1280,
    height: 720,
    usage: "Referencia visual para versión escritorio",
  },
  zafiro_dashboard_mobile_concept: {
    src: "/assets/zafiro/conceptos/zafiro-dashboard-mobile-concept.webp",
    alt: "Concepto de aplicación móvil ZAFIRO con núcleo, módulos y navegación inferior",
    width: 720,
    height: 1280,
    usage: "Referencia visual para versión móvil",
  },
  eliana_awakening_storyboard: {
    src: "/assets/zafiro/storyboards/eliana-awakening-storyboard.webp",
    alt: "Cuatro paneles del despertar y ascensión cósmica de ELIANA",
    width: 1080,
    height: 720,
    usage: "Storyboard de animación de despertar de ELIANA",
  },
} as const;

export type ZafiroAssetKey = keyof typeof ZAFIRO_ASSETS;