// Domain Data — Conocimiento autorizado de los 9 dominios
// MSM MY STORE LLC — Don Miguel Soria Martinez
// Frecuencia 369-777
// Cada entrada incluye fuente para trazabilidad

export interface DomainEntry {
  id: string
  domain: string
  title: string
  content: string
  source: string
  tags: string[]
  priority: number // higher = more important
}

export const DOMAIN_ENTRIES: DomainEntry[] = [
  // ─── 1. MSM MY STORE LLC ───
  {
    id: 'msm-01',
    domain: 'msm_my_store',
    title: 'MSM MY STORE LLC — Identidad Corporativa',
    content: 'MSM MY STORE LLC es una empresa registrada en Miami, Florida, Estados Unidos. Fundada y presidida por Don Miguel Soria Martinez. Es la entidad legal propietaria de todos los proyectos del ecosistema MSM: ZAFIRO, MSM Marketplace, MSM Editorial, MSM Economía, ELIANA, y todas las marcas, dominios y propiedad intelectual asociados. La empresa opera bajo la Frecuencia 369 como principio organizativo: Fe (3), Orden (6), Acción (9).',
    source: 'Documentos corporativos',
    tags: ['empresa', 'legal', 'estructura', 'msm'],
    priority: 10,
  },
  {
    id: 'msm-02',
    domain: 'msm_my_store',
    title: 'Don Miguel Soria Martinez — Fundador',
    content: 'Don Miguel Soria Martinez es el fundador, propietario y CEO de MSM MY STORE LLC. Correo: com8msm@gmail.com. Es el OWNER_SUPERADMIN con autoridad total sobre el ecosistema. Su perfil está sellado con membresía LIFETIME_UNLIMITED, estado ACTIVADO_Y_BLINDADO, y badges de FUNDADOR. Opera bajo las frecuencias 369 y 777.',
    source: 'owner.ts + migración 00008',
    tags: ['fundador', 'owner', 'ceo', 'don miguel'],
    priority: 10,
  },
  {
    id: 'msm-03',
    domain: 'msm_my_store',
    title: 'Ecosistema MSM — Los 4 Pilares',
    content: 'El ecosistema MSM se compone de 4 proyectos principales: 1) ZAFIRO — Red social del conocimiento, identidad digital, perfiles, VIP, KYC. 2) MSM Marketplace — Comercio electrónico con tiendas, pedidos y entregas. 3) MSM Editorial — Conocimiento con escritores, libros y devocionales. 4) MSM Economía — Operativa financiera con caja e inventario privado. Cada pilar tiene su propia base de datos independiente y se integran vía APIs y Eventos.',
    source: 'AGENTS.md — Orden Maestra',
    tags: ['ecosistema', 'pilares', 'arquitectura'],
    priority: 9,
  },
  {
    id: 'msm-04',
    domain: 'msm_my_store',
    title: 'Dominio oficial y despliegue',
    content: 'El dominio oficial del ecosistema es msmmystore.com. ZAFIRO está desplegado en https://zafiro.msmmystore.com con CNAME apuntando a Vercel. HTTPS funciona correctamente (200 OK). El sitio está construido con Next.js 16 y desplegado en Vercel.',
    source: 'AGENTS.md + verificación DNS',
    tags: ['dominio', 'despliegue', 'vercel', 'dns'],
    priority: 7,
  },

  // ─── 2. REMESAS CAMBIOS DIVISAS TASAS ───
  {
    id: 'rem-01',
    domain: 'remesas_cambios',
    title: 'Servicios de Remesas MSM',
    content: 'MSM MY STORE LLC ofrece servicios de envío y recepción de remesas entre Estados Unidos y Cuba. Los servicios disponibles incluyen: envío de divisas (USD, EUR, MLC), recogida en efectivo en Cuba, depósito en cuentas bancarias cubanas, y entrega a domicilio. Las operaciones se realizan a través de la red de Cajeros MSM y corresponsales autorizados. Para iniciar una remesa se requiere: moneda de origen, monto, moneda de destino, ubicación del remitente, ubicación del receptor, y datos del receptor.',
    source: 'Política activa de MSM Economía',
    tags: ['remesas', 'envio', 'cuba', 'divisas'],
    priority: 10,
  },
  {
    id: 'rem-02',
    domain: 'remesas_cambios',
    title: 'Tasas de Cambio — Cuba',
    content: 'Las tasas de cambio para Cuba se actualizan periódicamente según el mercado. El módulo de tasas está disponible en /admin/tasas con calculadora MSM integrada. El BPA Mirror (Banco Popular de Ahorro) versión 1.0 también está disponible en /admin/bpa. Las tasas aplicables incluyen: USD a CUP, USD a MLC, EUR a CUP, EUR a MLC. Las tasas varían según el método de entrega (efectivo, depósito, recogida en ventanilla). No se deben dar tasas sin verificar primero en el sistema.',
    source: 'tasas.ts + bpa-mirror.ts',
    tags: ['tasas', 'cambio', 'cup', 'mlc', 'divisas'],
    priority: 9,
  },
  {
    id: 'rem-03',
    domain: 'remesas_cambios',
    title: 'Operaciones Financieras — Reglas',
    content: 'Las operaciones financieras en el ecosistema MSM requieren autorización humana directa. ELIANA no puede: confirmar pagos sin verificación, aprobar transferencias, mover fondos entre cuentas, ni confirmar saldos sin consultar el ledger. ELIANA puede: explicar servicios disponibles, guiar sobre requisitos, consultar reglas vigentes, y preparar borradores de reportes para revisión humana.',
    source: 'owner-firewall.ts + system-prompt.ts',
    tags: ['reglas', 'seguridad', 'operaciones', 'autorizacion'],
    priority: 8,
  },

  // ─── 3. CATÁLOGO INVENTARIO CLIENTES VIP ───
  {
    id: 'cat-01',
    domain: 'catalogo_comercio',
    title: 'Catálogo de Productos MSM',
    content: 'MSM Marketplace ofrece un catálogo de productos y servicios dentro del ecosistema. Los productos se organizan por categorías y están disponibles para miembros según su nivel de membresía. El inventario se gestiona a través del módulo de Economía. Los clientes se clasifican por niveles: regular, VIP, y miembros del Círculo Élite. Cada nivel tiene condiciones y beneficios específicos.',
    source: 'zafiro-data.ts + módulo Economía',
    tags: ['catalogo', 'inventario', 'productos', 'marketplace'],
    priority: 7,
  },
  {
    id: 'cat-02',
    domain: 'catalogo_comercio',
    title: 'Membresías y Niveles VIP',
    content: 'ZAFIRO ofrece múltiples niveles de membresía. Los miembros VIP tienen acceso prioritario a contenido exclusivo, beneficios especiales en MSM Marketplace, tasas preferenciales en operaciones de cambio, y acceso anticipado a nuevos proyectos. La gestión VIP se realiza desde /admin/vip. Las membresías se procesan a través de Stripe con precios configurados en las variables de entorno STRIPE_PRICE_PRO y STRIPE_PRICE_CUBA_PLUS.',
    source: 'zafiro-data.ts + admin/vip',
    tags: ['vip', 'membresia', 'beneficios', 'stripe'],
    priority: 8,
  },

  // ─── 4. ZAFIRO ARQUITECTURA ───
  {
    id: 'zaf-01',
    domain: 'zafiro_arquitectura',
    title: 'ZAFIRO — Red Social del Conocimiento',
    content: 'ZAFIRO es una red social del conocimiento impulsada por IA, construida con Next.js 16, TypeScript, y Tailwind CSS. Utiliza App Router con todas las páginas en modo "use client". El tema es mobile-first con fondo oscuro #050816, acento #00D9FF, y tipografía Geist. Los iconos son de lucide-react y las animaciones de motion/react. El estado se persiste en localStorage con prefijo "zafiro_". El alias de rutas es @/* → ./src/*.',
    source: 'AGENTS.md + estructura del proyecto',
    tags: ['arquitectura', 'tech stack', 'next.js', 'zafiro'],
    priority: 9,
  },
  {
    id: 'zaf-02',
    domain: 'zafiro_arquitectura',
    title: 'Perfiles de Usuario en ZAFIRO',
    content: 'Los perfiles en ZAFIRO se gestionan con datos semilla en profile.ts. El perfil incluye: username, email, nombre, bio, avatar, rol, membresía, estado, PTS (Puntos de Sintonía), círculos, y badges. Los perfiles tienen caché invalidada al guardar mediante el evento "zafiro-profile-changed". El perfil de Don Miguel se siembra automáticamente con seedMiguelProfile(). Las rutas de perfil incluyen /mi-perfil, /perfil/[username], /profile-page, y /profile-page/edit.',
    source: 'profile.ts + zafiro-data.ts',
    tags: ['perfiles', 'usuarios', 'identidad', 'profile'],
    priority: 8,
  },
  {
    id: 'zaf-03',
    domain: 'zafiro_arquitectura',
    title: 'Círculos en ZAFIRO',
    content: 'Los Círculos son comunidades temáticas de élite dentro de ZAFIRO con contenido especializado. Cada círculo tiene su propio feed, miembros con roles, y contenido exclusivo. Los usuarios ganan acceso a círculos según su nivel de PTS y membresía. Los círculos disponibles incluyen: Ciencia, Tecnología, Gemología, y Círculo Élite (acceso total).',
    source: 'zafiro-data.ts',
    tags: ['circulos', 'comunidades', 'tematico', 'elite'],
    priority: 7,
  },
  {
    id: 'zaf-04',
    domain: 'zafiro_arquitectura',
    title: 'Sponsors en ZAFIRO',
    content: 'Los sponsors apoyan la infraestructura de ZAFIRO a cambio de visibilidad segmentada. El sistema de sponsors procesa pagos vía Stripe. Los sponsors actuales son: msmmystore.com, wa.me/17723015523, y el WhatsApp Channel de MSM. La página de sponsors se ha migrado a datos reales con stats dinámicos y botón para crear campañas.',
    source: 'sponsors-page + AGENTS.md',
    tags: ['sponsors', 'publicidad', 'stripe', 'monetizacion'],
    priority: 7,
  },
  {
    id: 'zaf-05',
    domain: 'zafiro_arquitectura',
    title: 'Gemología en ZAFIRO',
    content: 'La sección de Gemología (/gemologia) está especializada en el estudio de gemas: zafiros, rubíes, corindón, y otras piedras preciosas. Incluye información sobre propiedades, clasificación, valoración y authenticated certificación de gemas.',
    source: 'zafiro-data.ts + routes',
    tags: ['gemologia', 'gemas', 'zafiros', 'minerales'],
    priority: 6,
  },

  // ─── 4b. MEMBRESÍAS Y STRIPE ───
  {
    id: 'memb-01',
    domain: 'catalogo_comercio',
    title: 'Planes de Membresía ZAFIRO',
    content: 'ZAFIRO ofrece 3 planes de membresía: Gratis (acceso básico, 100 PTS/día), Pro ($9.99/mes o $7.99/mes anual, 500 PTS/día, círculos exclusivos, sin anuncios), y Cuba Plus ($14.99/mes o $11.99/mes anual, 1000 PTS/día, prioridad en remesas, tasas preferenciales). Los pagos se procesan mediante Stripe Checkout con webhook de confirmación. Ninguna membresía se activa sin verificación del webhook.',
    source: 'plans.ts — fuente única de verdad',
    tags: ['membresia', 'planes', 'precios', 'pro', 'cuba_plus'],
    priority: 9,
  },
  {
    id: 'memb-02',
    domain: 'catalogo_comercio',
    title: 'Activación de Membresía — Regla de Seguridad',
    content: 'Ninguna membresía se considera activa por mensaje de IA o por pantalla visual. Solo después de que Stripe envíe el webhook checkout.session.completed y ZAFIRO actualice la base de datos. Si el pago está pendiente, ELIANA responde "pago pendiente de confirmación". Si el webhook confirmó, responde "membresía activa". Si el pago falló, responde "pago no completado" y ofrece reintentar. Si hay discrepancia entre Stripe y ZAFIRO, escalar a Don Miguel.',
    source: 'memberships.ts + webhook route',
    tags: ['seguridad', 'activacion', 'stripe', 'webhook', 'regla'],
    priority: 10,
  },
  {
    id: 'memb-03',
    domain: 'catalogo_comercio',
    title: 'Stripe Integración Técnica',
    content: 'La integración con Stripe usa: Stripe Checkout para crear sesiones de pago, webhooks para eventos (checkout.session.completed, customer.subscription.*, invoice.*), y Customer Portal para gestión de suscripciones. Las claves se configuran en .env.local: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY, STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, NEXT_PUBLIC_STRIPE_PRICE_PRO, NEXT_PUBLIC_STRIPE_PRICE_CUBA_PLUS. El owner Don Miguel conserva membresía LIFETIME_UNLIMITED sin facturación.',
    source: 'stripe-server.ts + AGENTS.md',
    tags: ['stripe', 'pagos', 'checkout', 'webhook', 'api'],
    priority: 8,
  },

  // ─── 5. ELIANA IDENTIDAD MEMORIA ───
  {
    id: 'elia-01',
    domain: 'eliana_identidad',
    title: 'ELIANA — Identidad y Propósito',
    content: 'ELIANA (Engine for Learning & Intelligence AI Network Assistant) es el núcleo sintético de ZAFIRO. Versión 1.0.0, actualizada el 2026-07-17. Opera bajo la Frecuencia 369: Fe (3), Orden (6), Acción (9). Su propietario es MSM MY STORE LLC — Don Miguel Soria Martinez (com8msm@gmail.com). ELIANA no es un chatbot genérico sino un copiloto contextual del ecosistema MSM.',
    source: 'system-prompt.ts v1.0.0',
    tags: ['identidad', 'eliana', 'proposito', 'version'],
    priority: 10,
  },
  {
    id: 'elia-02',
    domain: 'eliana_identidad',
    title: 'ELIANA — Sistema de Intención (Intent Classifier)',
    content: 'ELIANA clasifica cada mensaje en 9 intents antes de procesarlo: chat_normal (conversación normal), greeting (saludo), training_json (owner envía JSON/entrenamiento), training_code (owner envía código), training_link (owner envía enlace), report_request (solicitud de reporte), financial (consulta financiera sensible), knowledge_query (pregunta sobre conocimiento específico), system_command (comando del sistema). El clasificador usa patrones regex y análisis contextual.',
    source: 'intent-classifier.ts',
    tags: ['intencion', 'clasificacion', 'intents', 'nlp'],
    priority: 9,
  },
  {
    id: 'elia-03',
    domain: 'eliana_identidad',
    title: 'ELIANA — Cortafuegos del Propietario (Owner Firewall)',
    content: 'El Owner Firewall implementa el protocolo STORE_ONLY: cuando Don Miguel envía JSON, código, plantillas o enlaces de entrenamiento, ELIANA almacena el contenido sin procesarlo como respuesta pública. Las consultas financieras son bloqueadas y requieren autorización humana directa. Todo se audita mediante recordOwnerAudit(). El sistema reconoce al owner mediante isOwnerSession() que verifica email contra isOwnerEmail().',
    source: 'owner-firewall.ts + owner.ts',
    tags: ['firewall', 'seguridad', 'owner', 'store_only'],
    priority: 9,
  },
  {
    id: 'elia-04',
    domain: 'eliana_identidad',
    title: 'ELIANA — Conocimiento y Memoria',
    content: 'ELIANA tiene acceso a 38 documentos de conocimiento organizados en 8 categorías: MSM, ZAFIRO, CAJEROS, MENTE_MAESTRA, LA_SUIZA, VILLA_ESPERANZA, ECONOMIA, WHATSAPP. El sistema usa chunking (textos divididos en segmentos <1800 caracteres con overlap de 100) y búsqueda por keywords con scoring. La base de conocimiento se gestiona desde /zafiro/admin/eliana/conocimiento donde se pueden subir, buscar, y eliminar documentos.',
    source: 'chunker.ts + retrieval.ts + knowledge-data.ts',
    tags: ['memoria', 'conocimiento', 'rag', 'chunking'],
    priority: 9,
  },
  {
    id: 'elia-05',
    domain: 'eliana_identidad',
    title: 'ELIANA — Feedback y Aprendizaje',
    content: 'ELIANA registra feedback de los usuarios mediante 5 acciones: Me gusta (like), Mejorar (improve) con comentario, Copiar (copy), Escuchar (listen con speechSynthesis), Enviar (send/share). Los comentarios de "Mejorar" se convierten automáticamente en reglas activas. Las reglas se almacenan en localStorage y se inyectan en el system prompt en cada conversación. El sistema mantiene hasta 1000 entradas de feedback y las reglas se pueden activar/desactivar manualmente.',
    source: 'feedback.ts + ResponseActionBar.tsx',
    tags: ['feedback', 'aprendizaje', 'reglas', 'mejora'],
    priority: 8,
  },
  {
    id: 'elia-06',
    domain: 'eliana_identidad',
    title: 'ELIANA — Proveedores de IA',
    content: 'ELIANA soporta múltiples proveedores de IA con failover automático: Gemini (gemini-1.5-flash, requiere GEMINI_API_KEY), OpenAI (gpt-4o-mini, requiere OPENAI_API_KEY), Anthropic (claude-3-haiku, requiere ANTHROPIC_API_KEY). Si un proveedor falla, prueba el siguiente en orden. Si todos fallan, devuelve respuesta vacía con provider "local" y modelo "fallback". Cada llamada tiene timeout de 30 segundos.',
    source: 'providers.ts',
    tags: ['ia', 'proveedores', 'gemini', 'openai', 'anthropic'],
    priority: 8,
  },

  // ─── 6. CAJEROS MSM PAYMENTS WALLET ───
  {
    id: 'caj-01',
    domain: 'cajeros_payments',
    title: 'Cajeros MSM — Red de Atención',
    content: 'Los Cajeros MSM son puntos de atención presencial para operaciones financieras del ecosistema, principalmente en Cuba. Gestionan recogida y entrega de efectivo, depósitos, y pagos. La red de cajeros es parte fundamental del servicio de remesas y operaciones de cambio.',
    source: 'zafiro-data.ts',
    tags: ['cajeros', 'presencial', 'cuba', 'efectivo'],
    priority: 7,
  },
  {
    id: 'caj-02',
    domain: 'cajeros_payments',
    title: 'MSM Payments — Sistema de Pagos',
    content: 'MSM Payments es el sistema de procesamiento de pagos del ecosistema. Integra Stripe para pagos internacionales y métodos locales para Cuba. Procesa membresías, compras, y remesas.',
    source: 'zafiro-data.ts',
    tags: ['pagos', 'payments', 'stripe', 'procesamiento'],
    priority: 7,
  },
  {
    id: 'caj-03',
    domain: 'cajeros_payments',
    title: 'MSM Wallet y Coins',
    content: 'MSM Wallet es la billetera digital del ecosistema. MSM Coins son tokens internos utilizados para transacciones dentro del ecosistema. El módulo de trading está disponible en /trading y /economia.',
    source: 'zafiro-data.ts + routes',
    tags: ['wallet', 'coins', 'tokens', 'billetera'],
    priority: 6,
  },

  // ─── 7. MENTE MAESTRA LA SUIZA VILLA ESPERANZA ───
  {
    id: 'proy-01',
    domain: 'proyectos_mentemaestra',
    title: 'Mente Maestra',
    content: 'Mente Maestra es un proyecto del ecosistema MSM enfocado en el desarrollo del conocimiento avanzado y la inteligencia colectiva. Es parte de los proyectos estratégicos de Don Miguel.',
    source: 'knowledge-data.ts',
    tags: ['mente_maestra', 'conocimiento', 'inteligencia', 'estrategico'],
    priority: 7,
  },
  {
    id: 'proy-02',
    domain: 'proyectos_mentemaestra',
    title: 'La Suiza de Cuba',
    content: 'La Suiza de Cuba es un proyecto inmobiliario y de desarrollo del ecosistema MSM. Representa una visión de infraestructura y comunidad en el contexto cubano.',
    source: 'knowledge-data.ts',
    tags: ['la_suiza', 'cuba', 'inmobiliario', 'desarrollo'],
    priority: 7,
  },
  {
    id: 'proy-03',
    domain: 'proyectos_mentemaestra',
    title: 'Villa Esperanza',
    content: 'Villa Esperanza es un proyecto comunitario y de desarrollo dentro del ecosistema MSM. Forma parte de la visión de impacto social y desarrollo comunitario de Don Miguel.',
    source: 'knowledge-data.ts',
    tags: ['villa_esperanza', 'comunitario', 'desarrollo', 'social'],
    priority: 7,
  },

  // ─── 8. ÁLBUM DE LA VIDA ───
  {
    id: 'album-01',
    domain: 'album_vida',
    title: 'Álbum de la Vida — Familia Soria Martínez',
    content: 'El Álbum de la Vida es el módulo familiar de ZAFIRO, accesible en /familia/* con 7 rutas. Incluye: Encuentro Soria Martínez (16-ago-2026), árbol genealógico, galería, cronología, historias, e invitación WhatsApp. Es la memoria digital de la familia Soria Martínez.',
    source: 'familia.ts + AGENTS.md',
    tags: ['familia', 'genealogia', 'album', 'soria_martinez'],
    priority: 8,
  },
  {
    id: 'album-02',
    domain: 'album_vida',
    title: 'Encuentro Soria Martínez 2026',
    content: 'El Encuentro de la Familia Soria Martínez está programado para el 16 de agosto de 2026. Se gestiona desde /familia/encuentro-2026 con invitaciones vía WhatsApp.',
    source: 'familia.ts + routes',
    tags: ['encuentro', 'reunion', '2026', 'invitacion'],
    priority: 8,
  },

  // ─── 9. PROGRAMACIÓN TÉCNICA ───
  {
    id: 'tech-01',
    domain: 'programacion_tecnica',
    title: 'Stack Tecnológico del Ecosistema',
    content: 'El ecosistema MSM está construido con: Next.js 16 (App Router, Turbopack), TypeScript, Tailwind CSS, motion/react para animaciones, lucide-react para iconos, y Supabase como backend (sin credenciales actualmente). El monorepo tiene 3 packages activos: eliana/, holo-cinema/, types/. El estado se maneja con localStorage (15+ keys con prefijo zafiro_). El build produce 0 errores y 97 rutas.',
    source: 'AGENTS.md + estructura del proyecto',
    tags: ['next.js', 'typescript', 'tailwind', 'supabase', 'stack'],
    priority: 9,
  },
  {
    id: 'tech-02',
    domain: 'programacion_tecnica',
    title: 'OpenCode y Codex',
    content: 'OpenCode es el asistente de IA utilizado para el desarrollo del ecosistema. El Codex es el conjunto de reglas y directrices de programación del proyecto. Las instrucciones se mantienen en AGENTS.md que documenta el estado actual, convenciones, rutas, y features del proyecto.',
    source: 'AGENTS.md + OpenCode',
    tags: ['opencode', 'codex', 'asistente', 'desarrollo'],
    priority: 8,
  },
  {
    id: 'tech-03',
    domain: 'programacion_tecnica',
    title: 'Despliegue y DevOps',
    content: 'El proyecto se despliega en Vercel con integración continua. El comando de build es "npm run build". El servidor de desarrollo se inicia con "npx next dev -p 3001". Los respaldos se crean con git bundle. La rama principal es main. La migración de base de datos está lista pero no aplicada por falta de credenciales de Supabase.',
    source: 'AGENTS.md + scripts',
    tags: ['devops', 'despliegue', 'vercel', 'git', 'backup'],
    priority: 7,
  },

  // ─── 10. LEGAL — Términos, Privacidad, Reglas Comunitarias ───
  {
    id: 'legal-01',
    domain: 'programacion_tecnica',
    title: 'Términos y Condiciones de ZAFIRO MSM',
    content: 'ZAFIRO MSM tiene términos y condiciones versionados que regulan: cuentas y perfiles, contenido del usuario, historias y perfiles, sponsors, IA ELIANA, servicios comerciales, privacidad y datos, seguridad, propiedad intelectual, y limitación de responsabilidad. La versión activa es v1.0 (Julio 2026). MSM MY STORE LLC puede actualizar los términos. El perfil owner (com8msm@gmail.com) pertenece al OWNER_SUPERADMIN.',
    source: 'terms-engine.ts — módulo legal versionado',
    tags: ['legal', 'terminos', 'condiciones', 'documentos'],
    priority: 8,
  },
  {
    id: 'legal-02',
    domain: 'programacion_tecnica',
    title: 'Política de Privacidad de ZAFIRO MSM',
    content: 'ZAFIRO MSM recopila datos necesarios para cuenta, seguridad, comunicación, servicios, analíticas y mejora de experiencia: nombre, correo, teléfono, perfil, dispositivo, IP aproximada, actividad. Los datos sensibles se protegen con controles adicionales. MSM no vende datos personales. Los datos se comparten con Stripe (pagos), Vercel y Supabase (infraestructura). El usuario puede acceder, corregir, eliminar y exportar sus datos.',
    source: 'terms-engine.ts — módulo legal versionado',
    tags: ['legal', 'privacidad', 'datos', 'proteccion'],
    priority: 8,
  },
  {
    id: 'legal-03',
    domain: 'programacion_tecnica',
    title: 'Reglas de la Comunidad ZAFIRO MSM',
    content: 'Las reglas comunitarias de ZAFIRO MSM establecen: respeto entre miembros, autenticidad de identidad, contenido apropiado, prohibición de spam, respeto a la privacidad, propiedad intelectual, reporte de contenido inapropiado, y consecuencias (advertencia, suspensión, cancelación).',
    source: 'terms-engine.ts — módulo legal versionado',
    tags: ['legal', 'reglas', 'comunidad', 'conducta'],
    priority: 7,
  },
  {
    id: 'villa-01',
    domain: 'programacion_tecnica',
    title: 'Villa Esperanza — Módulo Hospital Holístico',
    content: 'Villa Esperanza es un proyecto de hospital holístico en Las Siete Vueltas, Cuba. El módulo digital incluye: Villa Azul (villa principal con piscina infinita, 8 habitaciones, capacidad 16 personas, presupuesto $1.5M), Cabañas de Lujo (10 cabañas, $200-$500/noche, catálogo completo), Santuario Sagrado (espacio espiritual con agenda de actividades y normas), Árbol de la Vida (genealogía y memorial familiar, integrado con /familia), y Vistas 360 (recorridos virtuales). Meta financiera: $5,000,000 USD. Estado: EN_DESARROLLO. Fases: 6 fases de construcción. Rutas: /villa-esperanza/*.',
    source: 'villa-esperanza.ts — módulo de datos',
    tags: ['villa-esperanza', 'hospital', 'holistico', 'cuba', 'construccion', 'fases'],
    priority: 6,
  },
  {
    id: 'villa-02',
    domain: 'programacion_tecnica',
    title: 'Villa Esperanza — Financiamiento y Transparencia',
    content: 'El motor de financiamiento de Villa Esperanza maneja donaciones, inversiones, compromisos y patrocinios por separado. Reglas: toda entrada debe tener fuente, toda salida debe tener comprobante, no contar promesas como dinero recibido. Campañas activas: Fondo General ($5M), Villa Azul ($1.5M), Cabañas ($1.2M), Santuario ($800K). Dashboard en /admin/financiamiento. Transparencia: registro de aportes con verificación, auditoría de eventos, ledger público del fondo.',
    source: 'financiamiento.ts — motor de financiamiento',
    tags: ['villa-esperanza', 'financiamiento', 'donaciones', 'transparencia', 'campanas'],
    priority: 6,
  },
  {
    id: 'seguridad-02',
    domain: 'programacion_tecnica',
    title: 'Angel Security — Módulo de Seguridad',
    content: 'Angel Security es el módulo de seguridad central de ZAFIRO. Controles: roles y permisos (35 permisos, 10 roles incluyendo OWNER_SUPERADMIN, SYSTEM_ADMIN, FINANCE_ADMIN, CONTENT_ADMIN, SECURITY_AUDITOR, OPERATOR), auditoría inmutable append-only con máximo 10K entradas, rate limiting in-memory con bloqueo temporal tras 5 intentos en 60s, MFA device management (registro, revocación, máximo 10 dispositivos), validación de sesión, jerarquía de roles, schemas Zod para todas las entradas. Implementado en src/lib/angel-security.ts y src/lib/security-middleware.ts.',
    source: 'angel-security.ts — módulo core de seguridad',
    tags: ['seguridad', 'angel-security', 'permisos', 'roles', 'mfa', 'auditoria', 'rate-limit'],
    priority: 8,
  },
  {
    id: 'dashboard-01',
    domain: 'programacion_tecnica',
    title: 'Dashboard 360 — Estado del Ecosistema',
    content: 'El Dashboard 360 de Don Miguel en /admin/dashboard-360 muestra el estado completo del ecosistema: deployments activos (ZAFIRO OS, MSM My Store, MSM LegacyBook), dominios y su estado (msmmystore.com activo, market.msmmystore.com pendiente), seguridad (eventos, alertas críticas, rate limit hits), usuarios totales y VIP, auditoría reciente, alertas de seguridad, métricas de Villa Esperanza, KYC, operaciones y ELIANA.',
    source: 'dashboard-360/page.tsx',
    tags: ['dashboard', '360', 'monitoreo', 'estado', 'ecosistema', 'don-miguel'],
    priority: 6,
  },
  {
    id: 'clientes-01',
    domain: 'programacion_tecnica',
    title: 'Cliente Confiable — Protocolo de Confianza',
    content: 'El protocolo Cliente Confiable gestiona la identificación, riesgo y niveles de confianza de clientes MSM. Niveles: BASIC (registrado), VERIFIED (verificado), TRUSTED (confiable), VIP (alto valor), RESTRICTED (restringido). Datos permitidos: nombre, teléfono, correo, país, documento solo cuando proceda, historial de operaciones, nivel de riesgo, consentimientos. Prohibiciones: no guardar claves, PIN, semillas cripto ni publicar documentos. Memoria Eterna: historial autorizado de relación con el cliente con opción de corrección, descarga y eliminación. Panel en /admin/clientes-confiable.',
    source: 'cliente-confiable.ts — protocolo de confianza',
    tags: ['clientes', 'confianza', 'kyc', 'riesgo', 'niveles', 'memoria-eterna'],
    priority: 6,
  },
  {
    id: 'ledger-02',
    domain: 'programacion_tecnica',
    title: 'Ledger Maestro — Flujo Económico Centralizado',
    content: 'El Ledger Maestro de ZAFIRO gestiona el flujo económico completo: entradas y salidas de fondos, validación humana, sincronización con nodos, distribución a nodos operativos (CAJA_ROCIO, LIQUIDACION_VIP, FONDO_MSM, GENERAL), y cierre diario bloqueante. Monedas: USD, EUR, CUP, MLC, USDT. Métodos de pago: ZELLE, IBAN, CASH, USDT, VENMO. Cada operación pasa por 5 estados: PENDIENTE → VALIDADO → SINCRONIZADO → DISTRIBUIDO → CERRADO. Panel en /admin/ledger. Sincronizado con Logística de Contenedores (Frecuencia 369).',
    source: 'ledger.ts — ledger maestro',
    tags: ['ledger', 'economia', 'finanzas', 'contabilidad', 'cierre', 'nodos', '369'],
    priority: 7,
  },
  {
    id: 'marketing-01',
    domain: 'programacion_tecnica',
    title: 'Marketing Mayarí Arriba — Activos Promocionales',
    content: 'El módulo de Marketing gestiona los activos promocionales del ecosistema MSM. Incluye: 7 stickers angelicales (Ángel Guardián ZAFIRO, Logo ZAFIRO Dorado, Frecuencia 369, Ángel de la Abundancia), anuncio 8K del ecosistema con versiones para Facebook (horizontal), Instagram/Reels (vertical), estado de WhatsApp, y Telegram. Kit de marca: colores (azul zafiro #00D9FF, dorado #FFD700, azul noche #050816), tipografía Geist, reglas de uso. Panel en /admin/marketing.',
    source: 'marketing.ts — activos de marketing',
    tags: ['marketing', 'stickers', 'anuncios', 'brand-kit', 'mayari-arriba'],
    priority: 5,
  },
]
